/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xc_jnitest_exercise_JniTest */

#ifndef _Included_com_xc_jnitest_exercise_JniTest
#define _Included_com_xc_jnitest_exercise_JniTest
#ifdef __cplusplus
extern "C" {
#endif

jstring get (JNIEnv *, jobject);

void set (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
